FROM --platform=linux/amd64 python:3.11-slim
WORKDIR /app
COPY requirements-etl.txt .
RUN pip install --no-cache-dir -r requirements-etl.txt
COPY core/ core/
COPY etl/ etl/
CMD ["python", "etl/sync_whooing.py"]
