insert into app.card_benefit_rules (
  rule_id,
  card_account_type,
  card_account_id,
  name,
  status,
  priority,
  payment_channel,
  min_approval_amount,
  discount_type,
  discount_rate_bps,
  monthly_cap_tiers,
  performance_policy,
  posting_policy
) values
  (
    'shinhan_lady_lunch_5p',
    'liabilities',
    'x50',
    '신한 레이디 점심 5%',
    'active',
    20,
    null,
    null,
    'rate',
    500,
    '[]'::jsonb,
    '{"performanceAmountPolicy": "approval_amount", "manualSelection": true}'::jsonb,
    'reduce_expense'
  ),
  (
    'shinhan_lady_medical_5p',
    'liabilities',
    'x50',
    '신한 레이디 병원/약국 5%',
    'active',
    21,
    null,
    null,
    'rate',
    500,
    '[]'::jsonb,
    '{"performanceAmountPolicy": "approval_amount", "manualSelection": true}'::jsonb,
    'reduce_expense'
  ),
  (
    'shinhan_lady_shopping_3p',
    'liabilities',
    'x50',
    '신한 레이디 쇼핑 3%',
    'active',
    22,
    null,
    null,
    'rate',
    300,
    '[]'::jsonb,
    '{"performanceAmountPolicy": "approval_amount", "manualSelection": true}'::jsonb,
    'reduce_expense'
  )
on conflict (rule_id) do update set
  card_account_type = excluded.card_account_type,
  card_account_id = excluded.card_account_id,
  name = excluded.name,
  status = excluded.status,
  priority = excluded.priority,
  payment_channel = excluded.payment_channel,
  min_approval_amount = excluded.min_approval_amount,
  discount_type = excluded.discount_type,
  discount_rate_bps = excluded.discount_rate_bps,
  monthly_cap_tiers = excluded.monthly_cap_tiers,
  performance_policy = excluded.performance_policy,
  posting_policy = excluded.posting_policy,
  updated_at = now();
