import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

const source = readFileSync(resolve(import.meta.dirname, "imports-page.tsx"), "utf8");

test("imports page exposes review-first Excel dry-run and guarded automatic creation", () => {
  assert.match(source, /편한가계부 가져오기/);
  assert.match(source, /dry-run 비교/);
  assert.match(source, /자동등록 가능/);
  assert.match(source, /매핑 필요/);
  assert.match(source, /수정 후보/);
  assert.match(source, /삭제 후보/);
  assert.match(source, /충돌/);
  assert.match(source, /신규 확정 거래 자동 등록/);
  assert.match(source, /수정과 삭제는 단건 승인/);
  assert.match(source, /window\.confirm/);
  assert.match(source, /migration 미적용 상태/);
  assert.match(source, /새 자산·분류 후보/);
  assert.match(source, /승인금액/);
  assert.match(source, /할인액/);
  assert.match(source, /카드혜택 후보/);
  assert.match(source, /카드혜택 후보 승인/);
  assert.match(source, /승인 출처/);
  assert.match(source, /할인 출처/);
  assert.match(source, /복원 근거/);
  assert.match(source, /rule_reconstructed/);
  assert.match(source, /rule 선택 필요/);
  assert.match(source, /적합한 활성 rule 없음/);
  assert.match(source, /원장만 등록 가능/);
  assert.match(source, /\/api\/imports\/benefit-candidates\/select-rule/);
  assert.match(source, /선택 후 반영/);
  assert.match(source, /혜택만 반영/);
  assert.match(source, /검토 batch 저장/);
  assert.match(source, /후잉 원장은 수정하지 않고 app\.card_benefit_events에 혜택만 반영합니다/);
  assert.match(source, /기존 거래는 혜택만, 신규 거래는 매입금액 원장 등록 후 혜택 반영/);
  assert.match(source, /환급·캐시백·민생지원쿠폰은 review-only/);
  assert.match(source, /새 계정은 명확한 후보를 사용자가 승인한 경우에만 생성합니다/);
  assert.match(source, /Gmail 자동 감지/);
  assert.match(source, /Gmail dry-run 확인/);
  assert.match(source, /신규 거래 후보/);
  assert.match(source, /새 자산·매핑/);
  assert.match(source, /이체 후보/);
  assert.match(source, /수정 전 → 현재/);
  assert.match(source, /2개 편한가계부 row → 1개 Whooing transfer/);
  assert.match(source, /새 계정 생성 승인/);
  assert.match(source, /dry-run-only에서는 원장 변경이 비활성화됩니다/);
  assert.match(source, /\/api\/imports\/gmail\/poll/);
  assert.match(source, /Gmail은 읽기 전용입니다/);
  assert.match(source, /dry-run only/);
  assert.match(source, /event 누락/);
  assert.match(source, /금액 불일치/);
  assert.match(source, /benefitEventIntegrity/);
  assert.match(source, /최근 import batch/);
  assert.match(source, /정규화/);
  assert.match(source, /검토 필요/);
  assert.match(source, /현재 추가로 승인할 카드혜택 후보는 없습니다/);
  assert.match(source, /감지된 할인 거래는 모두 기존 event와 정상 연결되어 있습니다/);
  assert.match(source, /카드와 실제 할인율에 따라 확정 또는 rule 선택 필요 상태로 표시됩니다/);
  assert.match(source, /충돌·환급·캐시백·민생지원쿠폰은 review-only/);
  assert.match(source, /\/api\/imports\/actions\/register/);
  assert.match(source, /\/api\/imports\/actions\/approve-update/);
  assert.match(source, /\/api\/imports\/actions\/approve-delete/);
  assert.match(source, /삭제 승인/);
  assert.match(source, /window\.prompt/);
  assert.match(source, /confirmationText !== "원장 거래 삭제"/);
  assert.match(source, /원장 거래 삭제/);
  assert.match(source, /검토 대기/);
  assert.match(source, /\/api\/imports\/actions\/review/);
  assert.match(source, /\/api\/imports\/actions\/history/);
  assert.match(source, /Whooing 원장에 실제 등록/);
  assert.match(source, /검토 후 등록/);
  assert.match(source, /reviewConfirmed/);
  assert.match(source, /기존 계정에 매핑/);
  assert.match(source, /Whooing 거래를 실제 수정/);
  assert.match(source, /작업 이력/);
  assert.match(source, /새 계정 생성 승인/);
  assert.match(source, /Gmail 가져오기 실행/);
  assert.match(source, /safe 자동 반영/);
  assert.match(source, /최근 Gmail poll 결과/);
  assert.match(source, /계정\/매핑/);
  assert.match(source, /recommendedSectionId/);
  assert.match(source, /\/api\/imports\/actions\/create-account/);
  assert.match(source, /confirmed: true/);
});
