import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import test from "node:test";

const source = readFileSync(resolve(import.meta.dirname, "imports-page.tsx"), "utf8");

test("imports page exposes review-first Excel dry-run and guarded automatic creation", () => {
  assert.match(source, /편한가계부 가져오기/);
  assert.match(source, /dry-run 비교/);
  assert.match(source, /자동등록 가능/);
  assert.match(source, /매핑 필요/);
  assert.match(source, /수정 후보/);
  assert.match(source, /삭제 후보/);
  assert.match(source, /충돌/);
  assert.match(source, /신규 확정 거래 자동 등록/);
  assert.match(source, /수정·삭제 후보는 표시만 하며 자동 반영하지 않습니다/);
  assert.match(source, /window\.confirm/);
  assert.match(source, /migration 미적용 상태/);
  assert.match(source, /매핑 상태/);
  assert.match(source, /승인금액/);
  assert.match(source, /할인액/);
  assert.match(source, /카드혜택 후보/);
  assert.match(source, /카드혜택 후보 승인/);
  assert.match(source, /검토 batch 저장/);
  assert.match(source, /후잉 원장은 수정하지 않고 app\.card_benefit_events만 생성합니다/);
  assert.match(source, /원장 수정 없음, 카드혜택 event만 생성/);
  assert.match(source, /수입 의미가 섞여 있어 수동 정책 필요/);
  assert.match(source, /자동 삭제는 수행하지 않음/);
  assert.match(source, /Gmail 자동 감지/);
  assert.match(source, /Gmail dry-run 확인/);
  assert.match(source, /\/api\/imports\/gmail\/poll/);
  assert.match(source, /메일과 첨부를 읽기만 하며 후잉 원장은 변경하지 않습니다/);
  assert.match(source, /dry-run only/);
  assert.match(source, /최근 import batch/);
  assert.match(source, /정규화/);
  assert.match(source, /검토 필요/);
  assert.match(source, /현재 추가로 승인할 카드혜택 후보는 없습니다/);
  assert.match(source, /감지된 할인 거래는 모두 기존 event와 정상 연결되어 있습니다/);
  assert.match(source, /신규 할인 후보가 생기면 rule_matched 상태로 표시됩니다/);
  assert.match(source, /event 누락/);
  assert.match(source, /금액 불일치/);
  assert.match(source, /환급\/캐시백은 수입, 지출 환급, 카드 할인 중 의미가 섞일 수 있어 자동 처리하지 않습니다/);
  assert.match(source, /민생지원쿠폰 차액조정은 balance adjustment 또는 별도 지원금 처리 정책 확정 전까지 review-only입니다/);
});
